name: riverpod_devtools
description: DevTools extension for Riverpod - inspect and monitor your providers in real-time.
version: 0.0.1
repository: https://github.com/yutsuki3/riverpod_devtools

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1