name: riverpod_devtools_extension
description: DevTools extension UI for riverpod_devtools
publish_to: 'none'

version: 0.4.3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.3.0
  devtools_app_shared: ^0.3.0
  diff_match_patch: ^0.4.1
  vm_service: ^14.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



